set nocompatible

call plug#begin('~/.vim/plug')
Plug 'tpope/vim-surround'
Plug 'haya14busa/incsearch.vim'
Plug 'ctrlpvim/ctrlp.vim'
call plug#end()

filetype plugin indent on
syntax off

set autoindent
set clipboard=unnamed
set nocursorline
set nojoinspaces
set hidden
set ignorecase hlsearch smartcase
set shortmess+=aoOstTI
set shiftwidth=2
set expandtab tabstop=2
set mouse=a mousehide
set noerrorbells visualbell t_vb=
set completeopt=menu
set winminheight=0
set splitright
set backup
if has('persistent_undo')
    set undofile undolevels=1000 undoreload=10000
endif

nnoremap ! :!
map zl zL
map zh zH
map Q gq
map j gj
map k gk
map Y y$
vmap < <gv
vmap > >gv

autocmd BufWritePre <buffer> call StripTrailingWhitespace()
autocmd BufRead,BufNewFile *.md setlocal ft=markdown linebreak
autocmd FileType c,cpp,make,sh setlocal ts=8 sw=8 noet
autocmd FileType c,cpp setlocal cin fo=tcroqnl cino=:0,l1,t0,g0,(s,m1,j1,J1

set hlsearch
let g:incsearch#auto_nohlsearch = 1
map n <Plug>(incsearch-nohl-n)
map N <Plug>(incsearch-nohl-N)
map * <Plug>(incsearch-nohl-*)
map # <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

" Setup directories for backup, view and swap files under ~/.vim/.
function! InitializeDirectories()
    let parent = $HOME
    let prefix = 'vim/'
    let dir_list = {
    \   'backup': 'backupdir',
    \   'views': 'viewdir',
    \   'swap': 'directory',
    \}
    if has('persistent_undo')
        let dir_list['undo'] = 'undodir'
    endif
    let common_dir = parent . '/.' . prefix
    for [dirname, settingname] in items(dir_list)
        let directory = common_dir . dirname . '/'
        if exists("*mkdir")
            if !isdirectory(directory)
                call mkdir(directory)
            endif
        endif
        if !isdirectory(directory)
            echo "Warning: Unable to create backup directory: " . directory
            echo "Try: mkdir -p " . directory
        else
            let directory = substitute(directory, " ", "\\\\ ", "g")
            exec "set " . settingname . "=" . directory
        endif
    endfor
endfunction
call InitializeDirectories()

function! StripTrailingWhitespace()
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " Let's do this!
    %s/\s\+$//e
    " Cleanup: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
